services:
  web:
    container_name: fastapi-container
    build: .
    ports:
      - "8000:8000"

  redis:
    image: redis/redis-stack:6.2.6-v10
    container_name: my-redis-container
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - /redis-data:/data
    environment:
      REDIS_ARGS: "--requirepass jota123 --save 60 1000 --appendonly yes"
      

volumes:
  redis-data:
    driver: local