services:

  web:
    restart: on-failure
    hostname: fastapi
    build: ./backend
    ports:
      - "81:8000"
    volumes:
      - ./backend:/backend


  redis:
    image: redis/redis-stack:6.2.6-v10
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - /redis-data:/data
    environment:
      REDIS_ARGS: "--requirepass jota123 --save 60 1000 --appendonly yes"
      
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  redis-data:
    driver: local